### ISSUE TITLE
Documentation for packaging

### ISSUE THREAD

**Issue by casalot** [zendesk/app_scaffold#21]
The README covers everything from installation to running locally and testing. The area that is missing, is packaging and deployment.

I assume the following is still relevant for this repo:

``` bash
cd dist
zat validate
zat package
```

And, then manually uploading the .zip file from the `/tmp` to your Zendesk instance.

Testing by adding `?zat=true` to the URL.

**Comment by sandlerr** [comment]
Thanks for opening the issue @casalot we have made some improvements to the readme - please feel free to open more issues if there's more missing information.
