### ISSUE TITLE
Translations are not transferred to the "dist" folder on Windows, so app can't start

### ISSUE THREAD

**Issue by wcactus** [zendesk/app_scaffold#44]
Hello! I trying to use app_scaffold on Windows 10 x64 with ruby 2.3.3, node 6.9.2 and npm 3.10.9. When I run "nf start", server starts successfully, but no translation files appearing in dist/translations folder. So I got an error in browser's console when I trying to show app in zendesk's interface with "?zat=true". If i put translation file manually, app run successfully.

**Comment by mariasica** [comment]
@zendesk/i18n-dev

**Comment by corneliuskopp** [comment]
+1
Poking around webpack it seems that the `translation-loader` custom loader is not applied. Not just is there no feedback visible in the webpack output (even with the various **--display-foo** arguments), some `console.log()` statements in the loader aren't being emitted. Even a `throw` seems to cause no problems.

From my POV, either webpack isn't finding the loader, or without an entrypoint pointing at the translation files, it feels no reason to act?
