### ISSUE TITLE
Zendesk Garden references 'normalize.css' which is not found

### ISSUE THREAD

**Issue by joelhellman** [zendesk/app_scaffold#51]
Just cloned this repo and checked out the `from-scratch` branch, I get an error in chrome dev console: 
https://assets.zendesk.com/apps/sdk-assets/css/0/normalize.css 404 (Not Found), which comes from Zendesk Garden's stylesheet at https://assets.zendesk.com/apps/sdk-assets/css/0/zendesk_garden.css

**Comment by danielbreves** [comment]
@joelhellman this is a known issue with the Zendesk Garden asset, not specific to the App Scaffold, but thanks for reporting. It shouldn't prevent Zendesk Garden from working though. We'll ship a fix soon in any case.

**Comment by aculligan** [comment]
I've been using the CSS from the Zendesk Garden page (http://garden.zendesk.com/svg-icons/bedrock.css) any big difference there?

**Comment by nick-f** [comment]
@joelhellman A fix for normalize.css returning a 404 has been shipped. If you're using the CDN link it should be updated automatically. On the off chance your browser isn't reflecting the changes, a refresh on the file or clearing your browser cache should do the trick.

@aculligan The Garden site files are specific to that project. Those files are not versioned, whereas the assets CDN allows you to specify which version you wish to use. And the link you provided is returning a 404 now.
