### ISSUE TITLE
from-scratch branch does not include moment in the external js assets

### ISSUE THREAD

**Issue by StephenMP** [zendesk/app_scaffold#57]
The current webpack.config.js is as follows:
```
var externalAssets = {
  css: [
    'https://assets.zendesk.com/apps/sdk-assets/css/0/zendesk_garden.css'
  ],
  js: [
    'https://cdn.jsdelivr.net/g/lodash@4.14.0,handlebarsjs@4.0.5,jquery@3.1.0',
    'https://assets.zendesk.com/apps/sdk/2.0/zaf_sdk.js'
  ]
}
```

It should be:
```
var externalAssets = {
  css: [
    'https://assets.zendesk.com/apps/sdk-assets/css/0/zendesk_garden.css'
  ],
  js: [
    'https://cdn.jsdelivr.net/g/lodash@4.14.0,handlebarsjs@4.0.5,jquery@3.1.0,momentjs@2.18.1',
    'https://assets.zendesk.com/apps/sdk/2.0/zaf_sdk.js'
  ]
}
```

**Comment by danielbreves** [comment]
@StephenMP that was intentional. We didn't think moment was essential for most users, so we left it out, especially considering it's quite a large library. It can be added on a case by case basis. Will close this for now.

**Comment by StephenMP** [comment]
If it's intentional, then should it be removed from the Webpack config?

`  externals: {
    handlebars: 'Handlebars',
    jquery: 'jQuery',
    lodash: '_',
    moment: 'moment',
    zendesk_app_framework_sdk: 'ZAFClient'
  },`

to

`  externals: {
    handlebars: 'Handlebars',
    jquery: 'jQuery',
    lodash: '_',
    zendesk_app_framework_sdk: 'ZAFClient'
  },`

**Comment by danielbreves** [comment]
Oh yes, good catch!

**Comment by danielbreves** [comment]
https://github.com/zendesk/app_scaffold/pull/58

**Comment by StephenMP** [comment]
Glad to help :)
