### ISSUE TITLE
make this package

### ISSUE THREAD

**Issue by grosser** [zendesk/app_scaffold#76]
Unable to get my app to package ... and this one works neither ... weird issues and too-many-open-files ... plz add whatever is needed to make `zat package` work

@svizzari

**Comment by grosser** [comment]
@zendesk/vegemite I can haz a fix pls ? :)

**Comment by danielbreves** [comment]
@grosser did you run `zat package --path=dist` as per https://github.com/zendesk/app_scaffold#deploying?

**Comment by grosser** [comment]
yeah that's better ... now only failing on "    validate  Missing translation file for locale 'en'. Learn more: http://developer.zendesk.com/documentation/app"
... maybe add some sanity check into zat that it prints `use --path dist` when it runs in a path with node_modules

**Comment by grosser** [comment]
... also the docs link to v1 ... which is wrong ... right ?

**Comment by svizzari** [comment]
@grosser 

Hey, sorry didn't see your initial cc, must have been filtered.

> maybe add some sanity check into zat that it prints use --path dist when it runs in a path with node_modules

👍 I'll add a GH Issue/JIRA for this

**Comment by grosser** [comment]
got it working now ... found https://github.com/zendesk/zendesk_apps_tools/pull/214 ... and translation error vanished ... maybe caused by invalid json too ... thx for the help! :)
