### ISSUE TITLE
webpack -p error

### ISSUE THREAD

**Issue by rmrtnz89** [zendesk/app_scaffold#77]
When trying to run the zat migrate command I get the following error:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! app_scaffold@0.1.0 build: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the app_scaffold@0.1.0 build script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app_scaffold package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app_scaffold
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app_scaffold
npm ERR! There is likely additional logging output above.

Attaching the log file:
[npm-debug.log](https://github.com/zendesk/app_scaffold/files/1482309/npm-debug.log)

**Comment by rmrtnz89** [comment]
BTW, I am already in the last version of node.js and npm (8.9.1)

**Comment by danielbreves** [comment]
@rmrtnz89 It looks like this ran using Node v5.9.0. Do you have a node version manager? Could you check it's actually using the latest version? e.g. `nvm current` or `nodenv version`.
