### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by Mojachieee** [zendesk/app_scaffold#78]
When running the `default` app_scaffold app I get the following error in the Chrome's developer console and the app does not load.

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (i18n.js:58)
    at eval (i18n.js:59)
    at Object.<anonymous> (main.js:1)
    at n (main.js:1)
    at eval (index.js:4)
    at Object.<anonymous> (main.js:1)
    at n (main.js:1)
    at eval (app.scss:2)
    at Object.<anonymous> (main.js:1)
    at n (main.js:1)
(anonymous) @ i18n.js:58
(anonymous) @ i18n.js:59
(anonymous) @ main.js:1
n @ main.js:1
(anonymous) @ index.js:4
(anonymous) @ main.js:1
n @ main.js:1
(anonymous) @ app.scss:2
(anonymous) @ main.js:1
n @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
```

It seems to be due to mixing import and modules.exports with webpack
https://github.com/webpack/webpack/issues/4039

**Comment by danielbreves** [comment]
Hi @Mojachieee,

Apologies for the late reply.

I wasn't able to repro this on the master branch with Node v6.3.0 and webpack 3.10.0. Could you tell us what versions of Node and webpack you are using?

**Comment by Mojachieee** [comment]
I am no longer able to reproduce this issue, so I'll assume it was an environment error on my part
