### ISSUE TITLE
ZAFClient.init() returns false

### ISSUE THREAD

**Issue by ovvn** [zendesk/app_scaffold#79]
Going to http://localhost:4567/index.html
Getting `Uncaught TypeError: client.on is not a function` at https://github.com/zendesk/app_scaffold/blob/master/src/javascripts/index.js#L12
since `client` variable is `false` here https://github.com/zendesk/app_scaffold/blob/master/src/javascripts/index.js#L9

**Comment by danielbreves** [comment]
Hi @ovvn, that's expected. ZAFClient only works when your app is in iframe within the Zendesk application. For more info, see https://developer.zendesk.com/apps/docs/apps-v2/using_sdk#testing-an-app-locally.
