### ISSUE TITLE
How to use the app locally?

### ISSUE THREAD

**Issue by ovvn** [zendesk/app_scaffold#81]
I’m trying to test the app locally following the article at https://help.zendesk.com/hc/en-us/articles/229489288
I installed all prerequisites and successfully started the server on port 4567 but don’t know how to obtain the zendesk support url which according to the article should look something like this:
https://subdomain.zendesk.com/agent/tickets/321?zat=true
Should this subdomain be set up separately somewhere?

**Comment by danielbreves** [comment]
Hi @ovvn, this can be any Zendesk account. If you don't have one you can create a free trial [here](https://www.zendesk.com/register/#getstarted).
