### ISSUE TITLE
Can not package

### ISSUE THREAD

**Issue by jmolinap** [zendesk/app_scaffold#82]
When trying to package the app, i receive the following error message

    validate  Javascripts, stylesheets, and templates are not allowed when an iframe URI or noTemplate is specified

The app does not get packaged.

Any hints on why this issue is being shown and potential solution?

Thanks

**Comment by yu-tian113** [comment]
Hi @johnparra , we have published the new version scaffold with a completely rebuild. Please try out, any issues and contributions are welcome.
If you still need help with this issue, please leave a comment, we'll reopen and investigate asap.
