### ISSUE TITLE
resize function in breaking

### ISSUE THREAD

**Issue by Jayesh30** [zendesk/app_scaffold#85]
For top bar app, when we do switchTo any template , internally it called resize() from base_app.js, but percentage values are not supported when resizing top nav apps, so its breaking.

/code 

  let view = new View({
    afterRender: () => {
      // Automatically resize the iframe based on document height, if it's not in the "nav_bar" location
      if (**this._context.location !== "nav_bar"**) {
        let newHeight = Math.min($("html").height(), MAX_HEIGHT);
        this.zafClient.invoke("resize", { height: newHeight, width: "100%" });
      }
    }
  });

**Comment by yu-tian113** [comment]
Hi @Jayesh30, we have published the new version scaffold with a completely rebuild. Please try out, any issues and contributions are welcome.
