### ISSUE TITLE
Getting error when trying to run `nf start`

### ISSUE THREAD

**Issue by ratneshnavlakhe** [zendesk/app_scaffold#86]
[WARN] No ENV file found
11:38:55 AM reload.1 |  The CLI moved into a separate package: webpack-cli.
11:38:55 AM reload.1 |  Please install 'webpack-cli' in addition to webpack itself to use the CLI.
11:38:55 AM reload.1 |  -> When using npm: npm install webpack-cli -D
11:38:55 AM reload.1 |  -> When using yarn: yarn add webpack-cli -D
[DONE] Killing all processes with signal  null
11:38:55 AM reload.1 Exited with exit code 1
11:38:55 AM server.1 |  /Users/ratneshnavlakhe/.rbenv/libexec/rbenv-which: line 54: echo: write error: Broken pipe
11:38:55 AM server.1 Exited with exit code null

**Comment by danielbreves** [comment]
@ratneshnavlakhe what version of node are you running?

**Comment by ratneshnavlakhe** [comment]
Found the issue, I need to install the older version of webpack version 1.12.6 instead of newer one.
