### ISSUE TITLE
The nf start command doesn't work

### ISSUE THREAD

**Issue by johnparra** [zendesk/app_scaffold#91]
```nf start``` command does not work, when I run then does not make index.html file and another files.

I did install all dependencies {yarn, webpack and karma ...} in windows.

**Comment by fernfernfern** [comment]
Did you install foreman globally? That's the program that uses the Procfile. None of the other apps you mentioned will help with this. It's working for me on OSX.

**Comment by yu-tian113** [comment]
Hi @johnparra , we have published the new version scaffold with a completely rebuild. Please try out, any issues and contributions are welcome.

The `nf start` command uses the webpack version you installed globally, if it's different/incompatible with the version specified in the scaffold package.json, it may fail. Please try `npx webpack --watch` to see whether the build works.

If you still need help with this issue, please leave a comment, we'll reopen and investigate asap.
