### ISSUE TITLE
Cannot see any console log messages

### ISSUE THREAD

**Issue by fernfernfern** [zendesk/app_scaffold#92]
Hello, I'm looking for some advice on how to access the console log messages. I'm guessing they get eaten up because the app is running in an iframe. Do you know of any ways around this to see the console logs while the app runs?

**Comment by yu-tian113** [comment]
Hi @fernfernfern , we have published the new version scaffold with a completely rebuild. Please try out, any issues and contributions are welcome.
If you still need any help with this issue, please leave a message, we'll reopen and investigate asap
