### ISSUE TITLE
Location Folder and registered event.

### ISSUE THREAD

**Issue by meriadok** [zendesk/app_scaffold#97]
I don't understand how this new structure works, I created an additional file under /Locations named **new_ticket_sidebar.js**, my manifest only has one location, ticket_sidebar, but it still executes both scripts on /Location . Moreover, it registers the app 2 times, independent of the location.

Here I'm just console logging the appData object after the app.registered event fires:

![image](https://user-images.githubusercontent.com/15199847/46161290-8c82e080-c25b-11e8-8f6e-c221ccb03fd9.png)

`client.on('app.registered', function (appData) {
  client.invoke('app.hide');
  console.log(appData);
  return new App(client, appData);
});`

Event always fire twice for both scripts, even though I don't have new_ticket_sidebar as a location on my manifest.

**Comment by yu-tian113** [comment]
Hi @meriadok, looks like these two files are bundled together.
Please make sure `new_ticket_sidebar.js` is not imported as a dependency of `ticket_sidebar.js`, 
also if you planning to build for `new ticket sidebar` location,  in the webpack config, you should create a separate *entry*,

***WRONG***
```
entry: {
  app: [
    './src/javascripts/locations/ticket_sidebar.js',
    './src/javascripts/locations/new_ticket_sidebar.js',
    './src/index.css'
  ]
}
```

***CORRECT***
```
entry: {
  app: [
    './src/javascripts/locations/ticket_sidebar.js',
    './src/index.css'
  ],
  newticketsidebar: [
    './src/javascripts/locations/new_ticket_sidebar.js',
    './src/index.css'
  ]
}
```

**Comment by meriadok** [comment]
@yu-tian113 Thank you, the webpack entry was what I had wrong.
